# Add configuration values here, as shown below.

# to push to heroku:
# figaro heroku:set -e production
production:
  stripe_publishable_key: 'pk_live_JUxSvSw06avqgWj0eclLkZv0'
  stripe_secret_key: 'sk_live_k10m82GdfhJTeLr2dHncTdPW'

stripe_publishable_key: 'pk_test_GCMAWEnQDIiEVUYMYkO6xtjM'
stripe_secret_key: 'sk_test_t0tioKIAXM2IEOVow6X9eSLf'



